### ISSUE TITLE
Project 2 site - bottom staff list?

### ISSUE THREAD

**Issue by Zhadar1** [wws-haato/wws-haato.github.io#17]
Why is the staff list at the bottom of this project?

It should contain more info about the project, the same way it is for the first project
Our ideas for that project and what the lyrics are about as an example

**Comment by Leohsieh57** [comment]
that page is still WIP fyi

**Comment by Leohsieh57** [comment]
ah this one is because of 1 yr ago we said we'll put the full credit on the site so it was like this
https://grand-birthday-chorus.webflow.io/

but since webflow.io limits the number of pages to 2 per project and 2 projects per account 
I couldn't integrate this page into our previous website properly and thus got suspended

this is also why i choosed to switch to github.io and code everything myself this time

**Comment by Leohsieh57** [comment]
I'm not missing the description part, it's just because the credit list is already there so i put them there first
